CREATE TABLE IF NOT EXISTS rating
(
    rating_id    int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating_name  varchar(20) NOT NULL unique,
    rating_value varchar(20) NOT NULL unique
);

CREATE TABLE if not exists film
(
    film_id     Long GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name   varchar(150) NOT NULL,
    description text,
    releaseDate date         NOT NULL,
    duration    real         NOT NULL,
    rate        INTEGER,
    ratings     INTEGER      NOT NULL REFERENCES rating (rating_id)
);

create table if not exists filmUser
(
    user_id    Long GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_login varchar(20)  not null unique,
    user_name  varchar(150) not null,
    birthday   date,
    email      varchar(256) not null unique
);

CREATE TABLE IF NOT EXISTS genre
(
    genre_id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name varchar(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS user_friend
(
    user_id          long NOT NULL REFERENCES filmUser (user_id),
    friend_id        long NOT NULL REFERENCES filmUser (user_id),
    friendshipStatus boolean
);

CREATE TABLE IF NOT EXISTS film_genre
(
    film_id  Long NOT NULL REFERENCES film (film_id),
    genre_id int  NOT NULL REFERENCES genre (genre_id)
);

CREATE TABLE IF NOT EXISTS film_likes
(
    film_id Long NOT NULL REFERENCES film (film_id),
    user_id long NOT NULL REFERENCES filmUser (user_id)
);
