drop table if exists FILMORATE_USER, FILM_LIKES, USER_FRIEND, FILM, FILM_GENRE, MPA, GENRE;

CREATE TABLE IF NOT EXISTS MPA
(
    mpa_id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mpa_name varchar(20) NOT NULL unique
);

CREATE TABLE if not exists FILM
(
    film_id     Long GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name   varchar(150) NOT NULL,
    description text,
    releaseDate date         NOT NULL,
    duration    real         NOT NULL,
    rate        INTEGER,
    mpa         INTEGER      NOT NULL REFERENCES mpa (mpa_id)
);

create table if not exists FILMORATE_USER
(
    user_id    Long GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_login varchar(20)  not null unique,
    user_name  varchar(150) not null,
    birthday   date,
    email      varchar(256) not null unique
);

CREATE TABLE IF NOT EXISTS GENRE
(
    genre_id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name varchar(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS USER_FRIEND
(
    user_id          long NOT NULL REFERENCES FILMORATE_USER (user_id), --initiator
    friend_id        long NOT NULL REFERENCES FILMORATE_USER (user_id), --recipient
    friendshipStatus boolean
);

CREATE TABLE IF NOT EXISTS FILM_GENRE
(
    film_id  Long NOT NULL REFERENCES film (film_id),
    genre_id int  NOT NULL REFERENCES genre (genre_id)
);

CREATE TABLE IF NOT EXISTS FILM_LIKES
(
    film_id Long NOT NULL REFERENCES film (film_id),
    user_id long NOT NULL REFERENCES FILMORATE_USER (user_id)
);
